# Generated by Django 3.2.3 on 2021-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_unique_id', models.Field(max_length=50)),
                ('price', models.FloatField(verbose_name='Price')),
                ('date_of_transfer', models.DateTimeField(verbose_name='Date of Transfer')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('property_type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-detached'), ('T', 'Terraced'), ('F', 'Flats/Maisonettes'), ('O', 'Other')], default='O', max_length=1)),
                ('old_new', models.CharField(choices=[('Y', 'a newly built property'), ('N', 'an established residential building')], max_length=1)),
                ('duration', models.CharField(choices=[('F', 'Freehold'), ('L', 'Leasehold')], max_length=1)),
                ('paon', models.CharField(max_length=100, verbose_name='Primary Addressable Object Name')),
                ('saon', models.CharField(max_length=100, verbose_name='Secondary Addressable Object Name')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('locality', models.CharField(max_length=100, verbose_name='Locality')),
                ('town_city', models.CharField(max_length=100, verbose_name='Town/City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('ppd_category_type', models.CharField(choices=[('A', 'Standard Price Paid entry, includes single residential property sold for value.'), ('B', ' Additional Price Paid entry including transfers under a power of sale/repossessions, buy-to-lets (where they can be identified by a Mortgage) and transfers to non-private individuals.')], max_length=1)),
                ('record_status', models.CharField(blank=True, choices=[('A', 'Addition'), ('C', 'Change'), ('D', 'Delete')], max_length=1, null=True)),
            ],
        ),
    ]
